"""P2 보안 공통 모델 초기화

Revision ID: ad7e0a22b1a9
Revises:
Create Date: 2026-07-24 04:02:54.243576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad7e0a22b1a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.String(length=500), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('balance', sa.Integer(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("role in ('user','admin')", name='ck_user_role'),
    sa.CheckConstraint("status in ('active','dormant')", name='ck_user_status'),
    sa.CheckConstraint('balance >= 0', name='ck_user_balance_nonneg'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('actor_type', sa.String(length=8), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(actor_type = 'system' AND actor_id IS NULL) OR (actor_type in ('user','admin') AND actor_id IS NOT NULL)", name='ck_audit_actor'),
    sa.ForeignKeyConstraint(['actor_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dm_room',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_a_id', sa.String(length=36), nullable=False),
    sa.Column('user_b_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('user_a_id < user_b_id', name='ck_dm_room_order'),
    sa.ForeignKeyConstraint(['user_a_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_b_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_a_id', 'user_b_id', name='uq_dm_room_pair')
    )
    op.create_table('product',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('description', sa.String(length=4000), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('image_filename', sa.String(length=255), nullable=True),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("status in ('active','blocked','deleted')", name='ck_product_status'),
    sa.CheckConstraint('price > 0', name='ck_product_price_pos'),
    sa.ForeignKeyConstraint(['seller_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_product_title'), ['title'], unique=False)

    op.create_table('transfer',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('kind', sa.String(length=10), nullable=False),
    sa.Column('sender_id', sa.String(length=36), nullable=True),
    sa.Column('receiver_id', sa.String(length=36), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=200), nullable=False),
    sa.Column('idempotency_key', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(kind = 'transfer' AND sender_id IS NOT NULL AND sender_id <> receiver_id AND idempotency_key IS NOT NULL) OR (kind = 'grant' AND sender_id IS NULL)", name='ck_transfer_kind'),
    sa.CheckConstraint('amount > 0', name='ck_transfer_amount_pos'),
    sa.CheckConstraint('idempotency_key IS NULL OR length(idempotency_key) BETWEEN 16 AND 64', name='ck_transfer_idempotency_length'),
    sa.ForeignKeyConstraint(['receiver_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sender_id', 'idempotency_key', name='uq_transfer_idempotency')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('dm_room_id', sa.String(length=36), nullable=True),
    sa.Column('sender_id', sa.String(length=36), nullable=False),
    sa.Column('content', sa.String(length=500), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(scope = 'global' AND dm_room_id IS NULL) OR (scope = 'dm' AND dm_room_id IS NOT NULL)", name='ck_chat_scope_room'),
    sa.ForeignKeyConstraint(['dm_room_id'], ['dm_room.id'], ),
    sa.ForeignKeyConstraint(['sender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('report',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('reporter_id', sa.String(length=36), nullable=False),
    sa.Column('reported_user_id', sa.String(length=36), nullable=True),
    sa.Column('reported_product_id', sa.String(length=36), nullable=True),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('resolution', sa.String(length=16), nullable=True),
    sa.Column('reviewed_by', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint("(status in ('pending','auto_actioned') AND resolution IS NULL AND reviewed_by IS NULL AND reviewed_at IS NULL) OR (status = 'reviewed' AND resolution IS NULL AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL) OR (status = 'resolved' AND resolution in ('upheld','reversed','dismissed') AND reviewed_by IS NOT NULL AND reviewed_at IS NOT NULL)", name='ck_report_review_state'),
    sa.CheckConstraint("resolution is null or resolution in ('upheld','reversed','dismissed')", name='ck_report_resolution'),
    sa.CheckConstraint("status in ('pending','auto_actioned','reviewed','resolved')", name='ck_report_status'),
    sa.CheckConstraint('(reported_user_id IS NOT NULL) <> (reported_product_id IS NOT NULL)', name='ck_report_exactly_one_target'),
    sa.CheckConstraint('reported_user_id IS NULL OR reporter_id <> reported_user_id', name='ck_report_no_self_user'),
    sa.ForeignKeyConstraint(['reported_product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['reported_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reporter_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('reporter_id', 'reported_product_id', name='uq_report_product_once'),
    sa.UniqueConstraint('reporter_id', 'reported_user_id', name='uq_report_user_once')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report')
    op.drop_table('chat_message')
    op.drop_table('transfer')
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_product_title'))

    op.drop_table('product')
    op.drop_table('dm_room')
    op.drop_table('audit_log')
    op.drop_table('user')
    # ### end Alembic commands ###
